version: "3"

services:
  adminer:
    environment:
      - VIRTUAL_HOST=adminer.${VIRTUAL_HOST},www.adminer.${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=adminer.${VIRTUAL_HOST},www.adminer.${VIRTUAL_HOST},
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}