version: "3"

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}-5.7
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:  
      - ./data/5.7:/var/lib/mysql
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
