version: "3"

services:
  adminer:
    container_name: ${COMPOSE_PROJECT_NAME}-adminer
    image: adminer:4.7
    restart: always
    environment:
      - VIRTUAL_HOST=adminer.${VIRTUAL_HOST}
    networks:
      - frontend
    depends_on:
      - mysql
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:  
      - ./data/mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

networks:
  frontend:
    external:
      name: nginx-proxy